export const config = {
  inactive: [
    { label: 'notes.important_note_title', tag: 'h3' },
    { label: 'notes.important_note', tag: 'p' },
    { label: 'notes.important_note2', tag: 'p' },
    { label: 'notes.important_note3', tag: 'p' },
    { label: 'notes.important_note4', tag: 'p' },
  ],
  activation: [
    { label: 'notes.important_note_title', tag: 'h3', class: 'content-title' },
    { label: 'notes.mfa_info_01', tag: 'p' },
    { label: 'notes.mfa_info_011', tag: 'p' },
    { label: 'notes.mfa_info_012', tag: 'p' },
    { label: 'notes.mfa_info_013', tag: 'p' },
    { label: 'notes.mfa_info_014', tag: 'p', style: 'b' },
  ],
  active: [
    { label: 'buttons.activate_2fa', tag: 'h3' },
    { label: 'notes.note', tag: 'p', style: 'b', isNote: true },
    { label: 'notes.mfa_info_02', tag: 'p', isNote: true },
    { label: 'notes.installation_instruction', tag: 'p' },
    { label: 'notes.installation_steps', tag: 'p' },
    { label: 'notes.download_ios', tag: 'a' },
    { label: 'notes.download_android', tag: 'a' },
    { label: 'notes.installation_steps2', tag: 'p' },
    { label: 'notes.installation_steps3', tag: 'p' },
  ],
  code: [
    { label: 'notes.important_note_title', tag: 'h3', class: 'content-title' },
    { label: 'notes.download_code_info', tag: 'p' },
    { label: 'notes.backup_codes', tag: 'p' },
    { label: 'notes.backup_codes_info', tag: 'p' },
    { label: 'notes.backup_codes_info2', tag: 'p', style: 'b' },
  ],
  backup: [
    { label: 'notes.backup_codes', tag: 'p' },
    { label: 'notes.important_codes_info', tag: 'p' },
    { label: 'notes.backup_codes_info2', tag: 'p', style: 'b' },
  ],
};
